name: deep-research-4x-daily

on:
  schedule:
    # JST 08:00 = 前日 23:00 UTC
    - cron: "0 23 * * *"
    # JST 12:00 = 03:00 UTC
    - cron: "0 3 * * *"
    # JST 17:00 = 08:00 UTC
    - cron: "0 8 * * *"
    # JST 21:00 = 12:00 UTC
    - cron: "0 12 * * *"
  workflow_dispatch: {}   # 手動実行ボタンも出す

# 複数トリガーが近接した場合の重複実行を防ぐ（キューに積む）
concurrency:
  group: deep-research
  cancel-in-progress: false

jobs:
  research:
    runs-on: ubuntu-latest
    timeout-minutes: 30   # Deep Researchは数分〜十数分かかる想定
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install --upgrade openai

      - name: Run Deep Research (high quality)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DR_MODEL: o3-deep-research   # ← 高品質モードを明示
          DR_BASE_CODE: "6210"         # ← 6210から順番に進める（スクリプト側でGITHUB_RUN_NUMBER基準）
          DR_OUTDIR: outputs
        run: python run_research.py

      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          # 実行番号で一意に（スクリプト側のファイル名は銘柄コードとJST時刻入り）
          name: equity-report-${{ github.run_number }}
          path: outputs/*.md
          retention-days: 30
